
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://dragonchain.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Super Happy Dragon Lucky"
title: "Dragonchain"
description: "Dragonchain Organization Website"
keywords: "Dragonchain, Blockchain, Bitcoin, Cryptocurrency, Technology, Software"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/beta.png"

background-img: "/img/orion.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 5
start-delay: 100
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Blockchains are Magic!"
  - text: "Bitcoin is a remarkable cryptographic achievement. -- Eric Schmidt"
  - text: "You can’t stop things like Bitcoin. It will be everywhere and the world will have to readjust -- John McAfee"
  - text: "Every informed person needs to know about Bitcoin because it might be one of the world’s most important developments -- Leon Luow"
  - text: "The consequences of this breakthrough [Bitcoin] are hard to overstate. -- Marc Andresson"
  - text: "Anáil nathrach orth bhais betha, do cheol déanta"

me-img: "/img/mascot.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

#disqus-shortname: "dragonchain"

syntax-highlight: True

############
# Timeline #
############

#events:
#  - image: "/img/timeline/spidertocat.png"
#    date: "September 2013 - Today"
#    description: "Saving the neighborhood!"
#  - image: "/img/timeline/baracktocat.jpg"
#    date: "September 2007 - August 2013"
#    description: "Started coding"

# First image of the Timeline

#timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "info@dragonchain.org"
support_email: "support@dragonchain.org"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Blockchains are magic!"
author_blurb_image: "/img/mascot.png"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
  - title: "github"
    url: "https://github.com/dragonchain/dragonchain"
  - title: "slack"
    url: "https://dragonchain.slack.com"
  - title: "twitter"
    url: "https://twitter.com/dragonchaingang"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/icon.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Goals: 'goals'
  News: 'latest-post'
#  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
